### ISSUE TITLE
Update Fedora Python Packaging Guidlines

### ISSUE THREAD

**Issue by ncoghlan** [fedora-python/fedora-python#2]
Making a public place to collect notes for the next packaging guidelines update:

- clarify setup.py only builds vs pyproject.toml compatible builds (see https://lists.fedorahosted.org/archives/list/python-devel@lists.fedoraproject.org/thread/ZNLQJ4KVJRVWBCLHFGCX5KCTJDESQ5DA/ for discussion)
- clarify use of `Provides: bundled(...)` to declare unpatched bundled Python packages (see https://src.fedoraproject.org/rpms/python-pip/pull-request/1 for discussion)

**Comment by hroncok** [comment]
Closing, we are no longer using this repo.

See also https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/ZCNUQBJLDUJUJXK2EOPP2MWL6FJKLBPS/

We also use `bundled()` in pip now.
